"""Add facilities and rooms_facilities tables

Revision ID: 4d6ec12aba6d
Revises: 7697ac3fa844
Create Date: 2025-01-12 12:48:46.033062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d6ec12aba6d"
down_revision: Union[str, None] = "7697ac3fa844"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
