"""Added hotel_id to rooms

Revision ID: 334c76fcfc9d
Revises: a194706a882b
Create Date: 2025-01-05 13:57:09.242431

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "334c76fcfc9d"
down_revision: Union[str, None] = "a194706a882b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("hotel_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "rooms", "hotels", ["hotel_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rooms", type_="foreignkey")
    op.drop_column("rooms", "hotel_id")
    # ### end Alembic commands ###
