"""Add hotel_id to rooms

Revision ID: 6c94046e9f0b
Revises: 4d161d0ed2c9
Create Date: 2025-01-02 15:25:58.519667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c94046e9f0b"
down_revision: Union[str, None] = "4d161d0ed2c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("room_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "rooms", ["room_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rooms", type_="unique")
    op.drop_column("rooms", "room_id")
    # ### end Alembic commands ###
