"""Add hotel_id to rooms

Revision ID: a16becc1a917
Revises: deccbeb3652d
Create Date: 2025-01-02 13:17:49.194888

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a16becc1a917"
down_revision: Union[str, None] = "deccbeb3652d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("hotels_id", sa.Integer(), nullable=False))
    op.alter_column(
        "rooms",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.drop_constraint("rooms_hotel_id_fkey", "rooms", type_="foreignkey")
    op.create_foreign_key(None, "rooms", "hotels", ["hotels_id"], ["id"])
    op.drop_column("rooms", "hotel_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column("hotel_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "rooms", type_="foreignkey")
    op.create_foreign_key(
        "rooms_hotel_id_fkey", "rooms", "hotels", ["hotel_id"], ["id"]
    )
    op.alter_column(
        "rooms",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("rooms", "hotels_id")
    # ### end Alembic commands ###
