"""Updated data_from and data_to columns

Revision ID: 7697ac3fa844
Revises: a1ac4e8d00dd
Create Date: 2025-01-10 14:31:05.169662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7697ac3fa844"
down_revision: Union[str, None] = "a1ac4e8d00dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
