"""Add hotel_id to rooms

Revision ID: 0ced3099e012
Revises: 098dacad9cd3
Create Date: 2025-01-02 16:28:27.575476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ced3099e012"
down_revision: Union[str, None] = "098dacad9cd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("rooms_room_id_key", "rooms", type_="unique")
    op.drop_column("rooms", "room_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms", sa.Column("room_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint("rooms_room_id_key", "rooms", ["room_id"])
    # ### end Alembic commands ###
