"""Add hotel_id to rooms

Revision ID: 4d161d0ed2c9
Revises: f25ec088bc6d
Create Date: 2025-01-02 15:21:12.010855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d161d0ed2c9"
down_revision: Union[str, None] = "f25ec088bc6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
